src/view/components/utils.ts

The animation is too slow and distracting when the element picker is used.

Don't animate scroll in tree view

---

README.md

This is a minor improvement to the README, to help orient new users of the devtools.
As far as I can tell, this repository doesn't mention that you need to import `preact/debug`, so I've done my best to amend that. I used the same wording as the Preact guide here: <https://preactjs.com/guide/v10/debugging#installation>
Let me know if you have any feedback. Thanks!

Add usage guide to README.md

---

src/adapter/10/renderer.test.tsx
src/adapter/10/vnode.ts

We didn't set a fallback name for arrow function components which may have an empty string as `function.name`. Found while debugging #61 :tada:

Set fallback component name

---

src/view/components/elements/TreeView.css
src/view/components/elements/TreeView.tsx
src/view/components/tree/windowing.test.ts
src/view/components/tree/windowing.ts
src/view/components/utils.ts
src/view/store/index.ts
src/view/store/props.ts
src/view/store/types.ts

Main point is that the user never has to scroll horizontally :tada: 
Bugs:

Adapt indentation based on available screen space

---

src/adapter/10/renderer.ts
src/adapter/10/utils.test.tsx
src/adapter/10/utils.ts
src/examples/10/Circular.tsx
src/examples/10/setup.tsx
src/view/components/DataInput/parseValue.ts
src/view/components/sidebar/ElementProps.tsx
src/view/components/sidebar/parseProps.test.ts
src/view/components/sidebar/parseProps.ts

Up to know we didn't have any sort of protections against circular references. This can happen quite frequently in `props` when context is in play and would lead to infinite loops. With this PR we display any circular references as `[[Circular]]` similar to browsers.
This PR is work in progress.
Fixes #79 .

Fix infinite loop on circular references in props

---

rollup.config.js
src/shells/chrome/manifest.json
src/shells/edge/manifest.json
src/shells/firefox/manifest.json
src/shells/shared/initClient.ts
tools/build.js

The only reliable way to ensure that injected code is run before the page's js is by setting the script tag's `textContent` directly insteadof setting the "src"-attribute. Using the `src` attribute will lead to a race condition between our script tag and the page's js.
Fixes #85 .

Fix race condition when injecting devtools hook

---

src/adapter/adapter/picker.ts
src/adapter/events/events.ts
src/view/components/IconBtn.tsx
src/view/components/elements/TreeBar.tsx
test-e2e/test-utils.ts
test-e2e/tests/inspect-click.test.ts
test-e2e/tests/inspect.test.ts

Thanks to the new e2e test framework this was quite easy to debug and fix :tada: 
- Fix Infinite loop by triggering the same event again
- Fix don't trigger any app events when the picker is active

Fix inspect picker not working anymore

---

src/adapter/adapter/adapter.ts
src/adapter/adapter/picker.ts
src/view/components/elements/TreeView.tsx
src/view/store/index.ts
test-e2e/tests/element-keyboard.test.ts
test-e2e/tests/inspect-select.test.ts

Refactor the inspection picker code to be less error prone. By making it more push-oriented some errors are automatically resolved like a case where we could run into an infinite loop.
- Fix infinite loop when new inspection finished
- Feature: Inspect during picking
- Fix keyboard navigation not loading inspect data

Refactor inspection to be less error prone

---

src/view/components/profiler/components/TimelineBar/TimelineBar.tsx
src/view/components/profiler/flamegraph/FlamegraphStore.ts
test-e2e/test-utils.ts
test-e2e/tests/fixtures/profiler-1.js
test-e2e/tests/profiler-ranked.test.ts

Basically this means that the gray nodes are not visible when in `ranked` mode in the profiler.

Only display nodes of the current commit in ranked view

---

src/adapter/10/renderer.ts
src/adapter/10/utils.test.tsx
src/adapter/10/utils.ts
src/adapter/10/vnode.ts
test-e2e/tests/fixtures/update-all.js
test-e2e/tests/update-copy.test.ts

Updates should never mutate props/state/context but instead create a new object.
Tasks:
Fixes #118 .

Fix updates mutating existing vnode properties

---

src/adapter/10/vnode.ts
test-e2e/tests/context-displayname.test.ts
test-e2e/tests/fixtures/context-displayName.js
test-e2e/vendor/preact/next/preact.js
test-e2e/vendor/preact/next/preactHooks.js

Note this requires a change to Preact before this can be merged. Without that there is no way to get a hold of the context object based on the Provider constructor.
Fixes #116 .

Add support for context displayName

---

src/view/components/DataInput/DataInput.test.tsx
src/view/components/DataInput/inputState.ts
src/view/components/DataInput/parseValue.test.ts
src/view/components/DataInput/parseValue.ts
src/view/components/sidebar/inspect/ElementProps.css
src/view/components/sidebar/inspect/ElementProps.tsx
test-e2e/tests/fixtures/truncate.js
test-e2e/tests/inspect-truncate.test.ts

Before: `[1,2,3,4] -> Array`
After: `[1,2,3,4] -> [1, 2, 3,...`
Fixes #33 .

Improve value preview

---

src/adapter/10/marks.ts
src/adapter/10/options.ts
src/adapter/10/renderer.test.tsx
src/adapter/hook.ts
src/view/components/sidebar/inspect/ElementProps.tsx

This PR collects performance timings for Chrome's native profiling tools. Currently this only works in Chrome and probably Edge. Haven't found a way to show them in Firefox.
This will measure the time it takes from `options._diff` to `options._diff`
Fixes #73 .

Add support for user timings API

---

src/adapter/10/utils.ts
src/adapter/adapter/adapter.ts
src/adapter/hook.ts
src/adapter/renderer.ts
src/view/components/sidebar/inspect/ElementProps.tsx
src/view/components/sidebar/inspect/NewProp.tsx
src/view/components/sidebar/inspect/PropsPanel.tsx
src/view/components/sidebar/inspect/parseProps.test.ts
src/view/components/sidebar/inspect/parseProps.ts
src/view/store/props.ts

This is in preparation for #143 . Some more refactorings are needed because hooks can have multiple elements with the same name at the same hierarchy level. The current parser doesn't support that. This PR is a step into that direction.

Minor props parser refactoring

---

src/adapter/10/renderer.ts
src/adapter/10/vnode.ts
src/adapter/adapter/highlight.ts
src/adapter/dom.ts
test-e2e/tests/fixtures/highlight-fragment.js
test-e2e/tests/inspect-fragment.test.ts

In scenarios where the root `vnode` is a component we'd only highlight the first DOM node.
```jsx
// Only A was highlighted when hovering "MyComponent"
function MyComponent() {
return (
<>
<div>A</div>
<div>B</div>
</>
)
}
```
The same bug happened for components which directly returned an array. Internally Preact will automatically wrap it with a `Fragment` which leads to the same issue as with the component above.
```jsx
// Only A was highlighted when hovering "MyComponent"
function MyComponent() {
return [
<div>A</div>,
<div>B</div>,
]
}
```
The main issue in our code was that we checked for a `_lastDomChild`, which was removed a while ago from Preact. Instead we iterate over the inspected `vnode` children backwards until we find a `vnode` with an attached DOM node.
Fixes one of the …

Fix only first DOM element highlighted on Fragments

---

src/adapter/adapter/adapter.ts
src/adapter/adapter/picker.ts
test-e2e/test-utils.ts
test-e2e/tests/fixtures/highlight-scroll.js
test-e2e/tests/inspect-scroll.test.ts

Whenever the user was in "inspection" mode and scrolled, the highlight overlay would be stuck to the same position relative to the viewport. It didn't match the originally inspected node anymore. I've tried updating the position on scroll, but that is very taxing performance wise. Even with debouncing it feels a bit laggy and unnatural.
So I checked how chrome does it and they remove the highlighter on scroll, but will enable it immediately on the next `mousemove` event. That's what this PR is doing too and it feels much smoother :+1: 
Fixes the second issue mentioned in #144 :tada:

Fix highlight stuck on scroll

---

src/view/components/sidebar/inspect/ElementProps.css

Hi, I found a small style issue. 
**Before:** 
**Now:**

fix(ElementProps.css): fix toggle alignment

---

package.json
src/view/components/Devtools.css
src/view/components/elements/TreeView.css
src/view/components/elements/TreeView.tsx
test-e2e/test-utils.ts
test-e2e/tests/element-scroll.test.ts
test-e2e/tests/fixtures/deep-tree.js

This was caused by the a wrapper around all elements which is used to determine the total width. The width is the main factor to consider when adapting the indentation to the available space.
Solution is to only do the measuring during resize and let all nodes stretch to the full width afterwards :+1: 
This PR fixes the last issue mentioned in #144 :tada:

Fix elements only clickable on text

---

src/view/components/elements/TreeView.test.tsx
src/view/components/elements/TreeView.tsx

Keys are often longer than component names and a long key would cause to shrink the indentation very quickly.

Limit key length display

---

src/adapter/10/renderer/hooks.ts
src/view/components/sidebar/inspect/parseProps.test.ts
src/view/components/sidebar/inspect/parseProps.ts
src/view/store/props.ts
test-e2e/test-utils.ts
test-e2e/tests/fixtures/hooks-depth-limit.js
test-e2e/tests/hooks/hooks-depth-limit.test.ts

This was caused by a bit of technical dept in our props parser. It wrongly determined node depth by looking at the amount of dots in the id. This PR removes that weird assumption and instead bases the depth on the actual tree hierarchy.

Fix hooks parsing error when value is shortened

---

src/view/components/profiler/flamegraph/FlameGraph.tsx
test-e2e/tests/sync-selection.test.ts

Sync selection from Profiler to Elements, but only when the user has clicked a node. This is done on a best effort basis as the Profiler may show nodes, which are not present in the current tree anymore.
Fixes #168 .

Sync (only user) selection Profiler -> Elements

---

src/examples/inline-devtools/setup.tsx
src/index.tsx
src/shells/inline/index.ts
src/shells/shared/panel/panel.ts
src/shells/shared/utils.ts
src/view/components/Devtools.tsx
src/view/components/profiler/flamegraph/FlameGraph.tsx
src/view/components/utils.ts
src/view/store/react-bindings.ts

In browser-extension land one has to keep track of multiple different `window` references. If you attach your event handlers to the wrong one, nothing will be emitted. What's more confusing is that the global `window` object is rarely the one you actually want, and I too fell victim to that.

Fix window resize event never triggered

---

src/view/components/profiler/flamegraph/FlameGraph.css
src/view/components/profiler/flamegraph/FlameGraph.tsx

This PR improves responsiveness for large flame graphs a lot by only doing complex animations on nodes that are within the viewport. Nodes that would be hidden are simply faded out, therefore skipping expensive `width` and text ellipsis calculations.
The performance improvement is very noticeable on my Dell XPS 13.

Make flame graph animations less demanding on GPU

---

src/view/components/profiler/flamegraph/FlameGraph.tsx
test-e2e/tests/profiler/profiler-ranked.test.ts

The total duration including children isn't of much value in this view mode.

Only show selftime in ranked Flamegraph

---

src/global.css
src/view/components/ComponentName/ComponentName.css
src/view/components/DataInput/DataInput.css
src/view/components/Devtools.css
src/view/components/elements/TreeView.css
src/view/components/sidebar/inspect/ElementProps.css

See: https://bugs.chromium.org/p/chromium/issues/detail?id=623842
As another plus the fallback monospace font on MacOS is pretty ugly.

Work around chrome monospace bug

---

src/view/components/Devtools.tsx

When running inside Chrome, the "Report Bug" link tries to navigate the devtools panel to GitHub which Chrome rejects. Adding `target="_blank"` to the link makes it open in a new tab.

Fix report bug link not working

---

src/shells/shared/background/background.ts

This is not necessary as panels are seemingly reset on each navigation request. Fixes the following error:
```txt
Unchecked lastError value: Error: Invalid tab ID: 9
```

Fix trying to set popup on closed tab

---

src/adapter/adapter/adapter.ts
src/adapter/hook.ts
src/shells/shared/panel/panel.ts
src/view/components/elements/TreeView.tsx
src/view/components/icons.tsx
src/view/components/profiler/components/SidebarHeader.tsx
src/view/components/sidebar/SidebarActions.tsx
src/view/store/types.ts

This PR syncs the selection from the browser's elements panel to our extension. The other direction isn't really possible, because syncing would always cause the active tab to switch to the native elements panel. Therefore we've introduced a button in the sidebar to do it on user action.

Sync selection

---

src/view/components/settings/Settings.css
src/view/components/settings/Settings.tsx

Remove the common headline to tidy up the available space

Remove common headline in settings

---

src/adapter/10/options.ts

Noticed this when playing around with some prefresh demos, but haven't found a way to reliably reproduce it in a test case.

Fix undefined component with prefresh

---

src/adapter/10/renderer.ts
test-e2e/tests/fixtures/highlight-text.js
test-e2e/tests/profiler/highlight-updates-text.test.ts

When "Highlight Updates" is enabled in settings we'd sometimes get an error that `dom.getBoundingClientRect()` is `undefined`. This happens because the `vnode.dom` pointer may point to a `Text` node. Those don't have the `getBoundingClientRect` method.
So the fix is to instead use the nearest `parentNode`.
Fixes #225 .

Fix error on highlighting text node

---

.changeset/ninety-jokes-joke.md
src/adapter/adapter/filter.ts
src/shells/shared/panel/panel.ts
src/shells/shared/panel/settings.ts
src/view/store/filter.ts

This PR saves the component filter view to the browser settings. They will be restored whenever the devtools panel is re-opened.
Fixes #246 .

Save component filters in browser settings

---

.changeset/neat-dragons-swim.md
src/adapter/10/renderer/inspectVNode.ts
src/adapter/adapter/adapter.ts
src/adapter/events/events.test.ts
src/view/components/sidebar/KeyPanel.css
src/view/components/sidebar/KeyPanel.tsx
src/view/components/sidebar/Sidebar.tsx
test-e2e/fixtures/index.html
test-e2e/fixtures/keys.js
test-e2e/tests/inspect-key.test.ts

This PR adds a new panel to the Elements sidebar to show the key of the selected `vnode`.

Display key in sidebar

---

.changeset/new-knives-doubt.md
src/view/components/sidebar/inspect/ElementProps.tsx

There will still be a scrollbar when elements are nested too deep in the sidebar, so we likely need a better long term solution, similar to what we do in the elements panel. For now this is a good enough workaround though.

Fix horizontal sidebar scroll on low depth

---

src/adapter/10/renderer.ts
src/adapter/10/vnode.ts
src/adapter/adapter/highlight.ts

Regression introduced by preactjs/preact-devtools#244 which checks nodeType of a maybe null value.
Basic fix is to check the null, but introduce a little more typing demonstrating how errors like this can be avoided. One new function isTextNode is a narrowing type guard. Doing the same thing inline unfortunately is not nearly as neat.
Drive-by unmix tabs and spaces for everyone's sanity.
Traceback from using latest devtools release:
```
Uncaught (in promise) TypeError: dom is null
updateHighlight (index):2571
mount (index):2609
update (index):2681
update (index):2668
update (index):2722
createCommit (index):2773
onCommit (index):2962
```
And just a general observation, the code has a lot of telling the type checker to shut up with `any` casts. It looks like importing at least `VNode` from …

Fix TypeError dom is null in updateHighlight

---

src/adapter/10/renderer.ts
src/adapter/10/renderer/renderReasons.ts
src/adapter/10/vnode.ts

Add return type to all helpers and fix up a couple of callsites to either use a precise call or note and cast.
Use cast to internal preact types in preference to any for accessing private attributes, where possible. Older aliases still require any.
As an experiment, seems like this might be somewhat useful and not too much magic required? Note the `TODO` that I wasn't sure on the answer from glancing over the preact hook code.

Refine types on vnode utility functions

---

.changeset/few-games-tease.md
src/adapter/10/renderer.ts
src/adapter/10/vnode.ts
test-e2e/fixtures/suspense.js
test-e2e/test-utils.ts
test-e2e/tests/highlight-margin.test.ts
test-e2e/tests/highlight-suspense.test.ts
test-e2e/tests/suspense.test.ts

This PR builds on the work in #260.
With these changes `Suspense` nodes are now correctly detected and displayed. Note that Preact versions <10.4.5 used a raw `Component` class as a wrapper which is visible here. Newer Preact versions use a `Fragment` for that which we'll filter out automatically.
There was one oddity in regards to the children of a `Suspense` vnode. They can't be cached as Preact modifies them outside the usual render cycle.

Fix Suspense nodes not recognized

---

.changeset/stale-clouds-rescue.md
src/adapter/10/renderer.ts
src/adapter/10/renderer/inspectVNode.ts
src/adapter/10/vnode.ts
src/adapter/MultiRenderer.ts
src/adapter/adapter/adapter.ts
src/adapter/events/events.test.ts
src/adapter/hook.ts
src/adapter/renderer.ts
src/view/components/ComponentName/index.tsx
src/view/components/icons.tsx
src/view/components/sidebar/SidebarActions.tsx
test-e2e/tests/suspense-toggle.test.ts

This PR adds a new button in the sidebar action area that can be used to suspend trees. On click it will search upwards for the nearest Suspense component and toggle the suspending state.

Add support for suspending components

---

.changeset/orange-numbers-vanish.md
src/adapter/10/filter.ts
test-e2e/fixtures/fragment-filter.js
test-e2e/tests/filter-fragment.test.ts

Used the wrong `Fragment` reference in our comparisons :see_no_evil:

Fix Fragments not filtered out

---

src/shells/shared/popup/disabled.html

Currently, the disabled popup looks like this (in Firefox):
I think it could be a nice quick win if it showed a sentence to remind the user how to enable the devtools in their project:
(The sentence is taken directly from the README.md)

Show usage info in the disabled popup

---

src/shells/firefox/manifest.json

Hello, 
Noticed this when scrolling through my extensions on Firefox:
Super minor copy/paste error.

fix: Firefox description

---

src/adapter/hook.ts

The latter has been marked as not recommended as it prevents
the browser from using in memory caches.
See: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/1.5/Using_Firefox_1.5_caching
Fixes #275

Use pagehide instead of unload

---

src/adapter/10/options.ts
src/adapter/10/renderer/hooks.ts
test-e2e/fixtures/hooks-name.js
test-e2e/fixtures/vendor/preact/use-debug-name/preact.js
test-e2e/fixtures/vendor/preact/use-debug-name/preactCompat.js
test-e2e/fixtures/vendor/preact/use-debug-name/preactDebug.js
test-e2e/fixtures/vendor/preact/use-debug-name/preactDevtools.js
test-e2e/fixtures/vendor/preact/use-debug-name/preactHooks.js
test-e2e/test-utils.ts
test-e2e/tests/hooks/hook-name.test.ts

This PR adds support for customizing native hook names via a `useDebugName` hook.
Fixes #280 
Marked as draft until https://github.com/preactjs/preact/pull/2952 is resolved.

Add support for useDebugName hook

---

src/adapter/hook.ts
src/shells/shared/panel/panel.ts

This was a tricky one! Basically Firefox and Chrome fire the `onNavigated` event at different times. Chrome fires it as soon as the user navigates away and before the page starts to load. This in my opinion is the expected result.
Firefox on the other hand fires that event seemingly at random _after_ all scripts are loaded. This leads to a weird situation where the user navigates, we setup a connection and push events to the extension and only after that Firefox notifies us that a navigation took place. This is way too late as events have already been pushed at this point.

Fix empty panel in Firefox

---

src/adapter/10/vnode.ts

This updates the `useContext()` hook state property (`_context`) to reflect it being renamed to `c` in preactjs/preact#3165.

Update useContext() hook state property for preactjs/preact#3165

---

src/adapter/hook.ts

Fixes https://github.com/preactjs/preact/issues/3504
This currently happens for 10.7.0 because the patch is under 1

fix hook detection when the patch is under 1

---

src/adapter/shared/traverse.ts
test-e2e/fixtures/apps/holes.jsx
test-e2e/tests/profiler/highlight-updates-holes.test.ts

Missed a check for placeholder nodes. This didn't pop up earlier because the children array was typed as `any[]`.
Fixes #352 .

Fix highlight error if child is a placeholder

---

src/view/components/profiler/flamegraph/modes/FlamegraphLayout.tsx
test-e2e/tests/profiler/flamegraph/utils.ts

Revert part of #358 to reduce the number of DOM nodes in the Profiler view. The changes in #358 would slow down rendering quite a bit when a few thousand nodes are visible.
In the long term I'm hoping to switch to a canvas based renderer, but that's a bigger task and will take more time.

Profiler: Reduce number of DOM nodes

---

src/view/components/profiler/components/CommitTimeline/CommitTimeline.tsx
src/view/components/profiler/flamegraph/modes/patchTree.ts
test-e2e/fixtures/apps/static-subtree.jsx
test-e2e/tests/profiler/flamegraph/profiler-static-subtree.test.ts

This ensures a better visual relationship between timings of nodes. Best explained with pictures.
Before:
After:

Resize static subtrees to available space

---

src/view/components/profiler/flamegraph/modes/patchTree.ts
test-e2e/fixtures/apps/render-reasons-memo.jsx

`Uncaught TypeError: Cannot read properties of undefined (reading 'end')` is thrown when we add another memoized component that contains mapped elements
Related to #343

Add another memoized component in test case

---

src/view/components/profiler/components/TimelineBar/TimelineBar.tsx
test-e2e/fixtures/apps/profiler-2.jsx
test-e2e/tests/profiler/ranked/profiler-ranked-selected.test.ts

The currently selected node will not be reset when it's not part of the next commit in `ranked` profiler mode.

Profiler(Ranked): Fix missing selection on commit change

---

src/shells/shared/utils.ts
src/view/components/elements/VirtualizedList.tsx
src/view/components/utils.ts
test-e2e/tests/profiler/ranked/profiler-ranked.test.ts

Improve layout measurement for virtualized lists

---

src/adapter/10/bindings.ts
src/adapter/11/bindings.ts
src/adapter/shared/bindings.ts
src/adapter/shared/hooks.ts

With the recent change in https://github.com/preactjs/preact/pull/3567 the rendering of stateful hooks changed a little. This PR updates our detection code for that.
Related https://github.com/preactjs/preact/pull/3575

Fix hooks inspection not working with 10.8.1

---

src/view/components/elements/useAutoIndent.ts

Still unable to reproduce it on my end, but this should ensure that at least the initial size is correct in case no `resize` event is fired.
Another attempt at resolving #387 .

Fire indent on init in case resize is not fired

---

test-e2e/fixtures/apps/hoc-update.jsx
test-e2e/test-utils.ts
test-e2e/tests/hoc-filter-update.test.ts

- Always use latest stable Preact version by default
- Await state updates in `hoc-update` test case

Test updates

---

src/view/sprite.svg

This is an error caused by the recent icon refactoring. It's only on `main` and not in a released version.

Fix wrong record icon

---

src/adapter/dom.ts
test-e2e/tests/highlight-iframe.test.ts

This was caused by a confusion between viewport relative and absolute coordinates.

Fix incorrect highlight bounds checks

---

package.json
test-e2e/fixtures/load-preact-version.ts
test-e2e/fixtures/utils.ts

This works when the `preact` repository is in the same parent folder as the one for `preact-devtools`.

Add support for loading preact from local repo

---

src/adapter/shared/renderer.ts
src/adapter/shared/serialize.test.tsx
src/adapter/shared/serialize.ts
src/view/components/DataInput/parseValue.test.ts
src/view/components/DataInput/parseValue.ts
src/view/components/sidebar/inspect/parseProps.test.ts
src/view/components/sidebar/inspect/parseProps.ts
src/view/components/sidebar/inspect/serializeProps.test.ts
src/view/components/sidebar/inspect/serializeProps.ts

I went with serializing bigints as an object with a type and value, but I'm open to other ideas for how to serialize them so they are JSON compatible.
I don't know why I needed to change the type of `setInCopy`, but the original type definition appears to have been incorrect.
I largely don't understand what most of the properties in `parseProps` are for, so I just tried to copy other parsers in a way that seemed reasonable. In particular, `editable` I set to `!forceReadonly` but this was really just a guess on my part.
I made a few changes to improve the type strictness of `JSONValue`. If these strictness increases are considered undesirable then everything except the addition of `JSONBigint` can be removed without causing problems.
Fixes #453

Adds support for serializing bigints.

---

tools/build-plugins/esbuild-plugins.mjs

I don't really understand why the build is doing name mangling of classes and grid areas, but it appears there is already some code to deal with it. Unfortunately, that code doesn't work as *sometimes* the name mangler is including a leading `_` and sometimes it is not. Luckily, the fix is easy, just include support for an optional leading `_` in the existing regexp.

Fixes bug in grid-areas.

---

src/adapter/shared/hooks.ts
test-e2e/tests/inspect-signal.test.ts

Hooks inspection does a faked render (similar to React) to be able to detect custom hooks. Because we were calling an incomplete set of option hooks this lead to the internal state in the signals addon referencing the wrong vnodes.
Fixes #456

Fix crash when inspecting signal hooks

---

src/shells/chrome/manifest.json
src/shells/edge/manifest.json
src/shells/shared/background/background.ts
src/shells/shared/content-script.ts
src/shells/shared/popup/popup.ts
tools/build.mjs

There are two key factors which make me very worried about moving to MV3:
1. MV3 Service worker breaks on auto update https://bugs.chromium.org/p/chromium/issues/detail?id=1271154#c81 - Still not fixed
2. Google having laid off a bunch of folks from the extension team
3. Google itself has [extended the MV2 support lifecycle](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/) which kinda hints that MV3 is not ready.
Overall, I'm very hesitant to be one of the early adopters as I can't afford the additional cost of maintenance and debugging of weird issues that the move to MV3 would likely entail. Happy to try again once MV3 is more stable.

Revert back to Manifest V2

---

package.json
src/debug.ts
src/global.d.ts
src/shells/shared/panel/panel.ts
src/view/store/index.ts
test-e2e/fixtures/vite.config.ts
tools/build-plugins/esbuild-plugins.mjs
tools/build.mjs
tools/test-setup.js

I can't exactly reconstruct why I accidentally uploaded a debug build for chrome yesterday when cutting a new version (see https://github.com/preactjs/preact-devtools/issues/467 ). My assumption is that I ran the `run:chrome` command which builds a debug extension and loads it into a fresh chrome instance. I typically always use that just before publishing to make a final smoke test check. Normally, I run the `build:chrome` command once that's done but it looks like I forgot that yesterday. That's very likely what happened yesterday.
To prevent such accidents in the future this PR makes a couple of changes:
- Always use separate directories for debug and non-debug builds
- Always add `-debug` suffix to zipped debug extensions
- Use a global variable that must be injected to toggle debug …

Always infer debug mode from flag

---

tools/build-plugins/esbuild-plugins.mjs

This further improves the regex so it would handle cases like this:
```
grid-area: S_atwa_switcher;
```
which I unfortunately got when I was building locally 😅

Fix: Handle more cases in grid-area manual substitution

---

src/adapter/marks.ts

I've noticed in browser traces at work that the devtools extension is showing up a lot in traces and is causing jank in our page. While it doesn't affect users, I don't want my team to get the wrong impressions about Preact's perf when they are browsing localhost with devtools installed. So this change is attempting to improve the perf of devtools hooks so that it doesn't impact the page.
Sample screenshot of what I see in browser traces:

Improve perf of diffed hook

---

src/adapter/10/bindings.ts

If a defaultValue is specified we would erroneously take that as the contextRef rather than the actual ref

Check for presence of __l

---

package-lock.json
package.json
src/shells/chrome/manifest.json
src/shells/edge/manifest.json
src/shells/firefox/manifest.json

Latest attempt to update the extension was rejected due to the `tabs` permission. It looks like it's not needed and I'm not sure why I've added it. Probably a leftover when trying to wrestle MV3.

Remove tabs permission

---

test-e2e/fixtures/load-preact-version.ts

Current setup assumes `${output}.map` always exists, which isn't quite the case for X; the `.mjs` output is a renamed copy of `.module.js`, includes the original sourcemap comment (pointing at `.module.js.map`) and all. We therefore don't provide a `.mjs.map` as it's not referenced and therefore unused.
`readFileSync` would then throw if it attempted to resolve any `.mjs` files for X (as the `test:e2e:git` script would do)

test: Correct source map resolution
