- README.md
> Fix Chrome extension link in README

- src/examples/10/DataTypes.tsx
- src/examples/10/setup.tsx
- src/view/components/DataInput/DataInput.css
- src/view/components/DataInput/DataInput.test.tsx
- src/view/components/DataInput/index.tsx
> Fix checkbox value converted to a string

- src/view/components/DataInput/DataInput.test.tsx
- src/view/store/react-bindings.test.tsx
- src/view/store/react-bindings.ts
> Fix stale useObserver value

- src/examples/10/DataTypes.tsx
- src/examples/10/setup.tsx
- src/view/store/props.test.ts
- src/view/store/props.ts
> Don't expand complex objects in sidebar by default

- src/adapter/adapter/highlight.ts
- src/examples/10/Highlighting.tsx
- src/examples/10/setup.tsx
- src/index.tsx
- src/view/components/Highlighter.css
- src/view/components/Highlighter.tsx
> Fix jumpy page on highlighting due to scrollbar

- src/view/components/DataInput/DataInput.css
- src/view/components/DataInput/index.tsx
- src/view/components/IconBtn.css
- src/view/components/IconBtn.tsx
- src/view/components/sidebar/NewProp.css
- src/view/components/sidebar/NewProp.tsx
Add some minor UI polishing. I'll likely do a more thorough pass when the featureset is more complete (before releasing `1.0.0`).
Fixes #34
> Minor UI polishing

- src/shells/shared/initClient.ts
> Only inject hook into html page

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/firefox/manifest.json
> Release 0.1.0

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/firefox/manifest.json
> Release 0.1.1

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/firefox/manifest.json
> Release 0.1.2

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
:tada: 
_Note: That it will take quite a bit of time until it's approved on extension stores._
> Release 0.1.3

- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
- src/shells/shared/initClient.ts
- tools/build.js
> Only inject devtools css when Preact was detected

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
> Release 0.1.4

- src/adapter/10/IdMapper.ts
- src/adapter/10/renderer.ts
- src/adapter/10/renderer/inspectVNode.ts
- src/adapter/10/renderer/logVNode.ts
- src/shells/inline/index.ts
Move some parts away from OOP-style programming as it makes the code harder to test. This is a long-term goal of mine with `preact-devtools` as a more functional style will make the extension easier to test. Currently certain parts require way too much mocking to be testable.
> Renderer refactor

- src/adapter/10/renderer.test.tsx
- src/adapter/10/renderer.ts
- src/adapter/10/utils.ts
- src/adapter/MultiRenderer.ts
- src/adapter/adapter/adapter.ts
- src/adapter/hook.ts
- src/adapter/renderer.ts
- src/shells/shared/background/background.ts
- src/shells/shared/content-script.ts
- src/shells/shared/panel/panel.ts
> Fix devtools losing state when re-opening them

- src/adapter/10/filter.ts
- src/adapter/adapter/filter.ts
- src/view/components/elements/TreeBar.css
- src/view/components/elements/TreeBar.tsx
- src/view/store/filter.ts
> Fix filters not working

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
> Release 0.2.0

- package.json
- src/adapter/setup.ts
- src/examples/10/Circular.tsx
- src/examples/10/DataTypes.tsx
- src/examples/10/DeepTree.tsx
- src/examples/10/Highlighting.tsx
- src/examples/10/Prime.tsx
- src/examples/10/TodoList.tsx
- src/examples/10/legacyContext.tsx
- src/examples/10/setup.tsx
- src/examples/10/state.tsx
- src/examples/Iframer.tsx
- src/examples/Iframes.tsx
- src/examples/preact-10.tsx
- src/examples/vendor/htm.tsx
- yarn.lock
As a preparation for more automatic e2e testing this PR ports the examples to `htm`
> Port examples to htm

- src/view/components/ComponentName/ComponentName.css
- src/view/components/ComponentName/index.tsx
- src/view/components/Devtools.css
- src/view/components/IconBtn.css
- src/view/components/IconBtn.tsx
- src/view/components/elements/TreeBar.css
- src/view/components/elements/TreeBar.tsx
- src/view/components/elements/TreeView.css
- src/view/components/icons.tsx
- src/view/components/profiler/components/SidebarHeader.tsx
- src/view/components/profiler/components/Tabs/Tabs.css
- src/view/components/sidebar/Sidebar.css
- src/view/components/sidebar/SidebarActions.tsx
- Adds more consistent spacing
- Replaces a few icons
> Minor design improvements

- src/view/components/Highlighter.css
- test-e2e/tests/highlighter.test.ts
> Fix highlight flickering

- test-e2e/index.html
- test-e2e/tests/fixtures/root-multi.js
- test-e2e/tests/root-multiple.test.ts
> Add test case for multiple roots

- src/adapter/10/renderer.ts
- src/adapter/10/vnode.ts
- test-e2e/tests/preact-10.0.0-rc.0/inspect-10.0.0-rc.0.test.ts
- test-e2e/vendor/preact/10.0.0-rc.0/preact.js
- test-e2e/vendor/preact/10.0.0-rc.0/preactHooks.js
This was caused by a change in mangling property names before releasing Preact X as final.
> Fix inspect highlight not working on preactjs.com

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
> Release 0.2.1

- src/view/components/sidebar/ElementProps.css
Fix a minor visual inconsistency in the props panel.
> Fix mixed font size in props panel

- src/adapter/10/renderer.ts
- src/adapter/10/utils.ts
- src/adapter/10/vnode.ts
- src/view/components/DataInput/parseValue.ts
- src/view/components/sidebar/ElementProps.tsx
- src/view/components/sidebar/NewProp.tsx
- src/view/components/sidebar/parseProps.ts
- test-e2e/tests/fixtures/non-vnode.js
- test-e2e/tests/inspect-non-vnode.test.ts
> Fix objects wrongly detected as vnodes

- test-e2e/test-utils.ts
- test-e2e/tests/collapse.test.ts
- test-e2e/tests/inspect-truncate.test.ts
Currently failing for the sidebar, need to check later.
> Add collapse test

- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
> Update version in manifest

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
> Release 0.4.0

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
> Release 0.5.0

- src/view/components/elements/TreeBar.tsx
- src/view/components/elements/TreeView.tsx
- test-e2e/tests/element-search-keyboard.test.ts
This PR fixes an accidental regression introduced with 7df6342fbe80758aef05413bee0137b02b6fb1b9 . This PR adds a test to ensure that we'll catch that in the future :tada: 
Fixes #162
> Fix tree item not scrolling into view in search

- src/adapter/adapter/adapter.ts
- src/adapter/hook.ts
- src/constants.ts
- src/view/components/profiler/components/TimelineBar/TimelineBar.tsx
- src/view/components/profiler/data/commits.ts
- src/view/components/profiler/flamegraph/FlamegraphStore.test.ts
- src/view/store/index.ts
- test-e2e/test-utils.ts
- test-e2e/tests/fixtures/profile-reload.js
- test-e2e/tests/profiler-reload.test.ts
> Add support for reload and profile

- package.json
- src/adapter/10/renderer/logVNode.ts
- src/adapter/adapter/adapter.ts
- src/adapter/debug.ts
- src/adapter/events/legacy/operationsV1.ts
- src/adapter/hook.ts
- src/adapter/setup.ts
- src/debug.ts
- src/index.tsx
- src/shells/shared/content-script.ts
- src/shells/shared/panel/settings.ts
- src/view/components/elements/TreeView.tsx
Thought that this would be part of the recommended preset, but looks like this isn't the case :S
> Always enable no-console linting rule

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
> Release 0.6.0

- .gitignore
- package.json
- tools/run-chrome.js
This makes local testing a little easier.
> Add support for custom persistent user profiles

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
> Release 0.6.1

- src/view/components/profiler/components/CommitInfo/DebugInfo.tsx
- src/view/components/profiler/components/Profiler.tsx
- src/view/components/profiler/components/RenderedAt/DebugNodeNav.tsx
Add debug information for the Profiler in debug mode. This helped my quite a lot to narrow down a few incorrectly position nodes. These will be compiled out for production builds.
> Debug panels

- src/adapter/10/utils.test.tsx
- src/adapter/10/utils.ts
- src/view/components/DataInput/parseValue.test.ts
- src/view/components/DataInput/parseValue.ts
- src/view/components/sidebar/inspect/parseProps.test.ts
- src/view/components/sidebar/inspect/parseProps.ts
- test-e2e/tests/fixtures/symbols.js
- test-e2e/tests/symbol-value.test.ts
> Fix symbol values not supported

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
> Release 0.6.2

- src/adapter/events/legacy/operationsV1.ts
- src/adapter/events/operations.ts
- test-e2e/tests/preact-10.0.0-rc.0/profiler-unmount-10.0.0-rc.0.test.ts
- test-e2e/tests/profiler/flamegraph/profiler-unmount.test.ts
We should never mutate the store!
> Fix profiler nodes getting lost due to mutations

- src/adapter/10/renderer.ts
- src/adapter/MultiRenderer.ts
- src/adapter/adapter/adapter.ts
- src/adapter/adapter/highlightUpdates.ts
- src/adapter/hook.ts
- src/adapter/renderer.ts
- src/shells/shared/panel/settings.ts
- src/view/components/CanvasHighlight/CanvasHighlight.css
- src/view/components/CanvasHighlight/CanvasHighlight.tsx
- src/view/components/Checkbox/Checkbox.css
- src/view/components/Checkbox/Checkbox.tsx
- src/view/components/Devtools.css
- src/view/components/profiler/data/commits.ts
- src/view/components/settings/Settings.css
- src/view/components/settings/Settings.tsx
- test-e2e/tests/fixtures/todo.js
- test-e2e/tests/profiler/highlight-updates.test.ts
> Add support for highlight updates

- src/adapter/events/events.ts
- src/shells/shared/panel/panel.ts
- src/view/components/CanvasHighlight/CanvasHighlight.tsx
This PR polishes the highlight updates integration. See the commit messages for a list of bugs fixed.
> Polish highlight updates

- src/view/components/CanvasHighlight/CanvasHighlight.css
See https://twitter.com/marvinhagemeist/status/1263506164144316416
> Safeguard against page messing with canvas

- src/adapter/10/renderer.ts
- src/adapter/MultiRenderer.ts
- src/adapter/events/events.ts
- src/adapter/events/operations.test.ts
- src/adapter/events/operations.ts
- src/adapter/hook.ts
- src/adapter/renderer.ts
- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
As @developit pointed out in https://github.com/preactjs/preact/pull/2503 it's much more elegant to inject the devtools hook into all frames. This will automatically make highlight positions correct and resolves the need to patch them.
Tested with codesandbox.
Fixes #207 .
> Add proper support for debugging iframes

- src/adapter/10/renderer.ts
- src/adapter/adapter/adapter.ts
- src/adapter/debug.test.ts
- src/adapter/debug.ts
- src/adapter/hook.ts
- src/adapter/renderer.ts
- src/shells/shared/panel/panel.ts
- src/view/components/icons.tsx
- src/view/components/profiler/components/SidebarHeader.tsx
- src/view/components/sidebar/SidebarActions.tsx
- src/view/store/types.ts
Adds an icon to the sidebar to jump to the component source in the debugger.
> Add support for view source

- src/adapter/10/renderer.ts
- src/adapter/MultiRenderer.ts
- src/adapter/adapter/adapter.ts
- src/adapter/hook.ts
- src/adapter/renderer.ts
- src/view/components/sidebar/Sidebar.css
- src/view/components/sidebar/SidebarActions.tsx
- Deprecate `force-update` event
- Adjust spacing
> Sidebar cleanup

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
> Release 0.7.0

- src/adapter/adapter/highlight.ts
- src/adapter/dom.ts
- test-e2e/tests/fixtures/highlight-margin.js
- test-e2e/tests/highlight-margin.test.ts
> Fix incorrect highlight offset with margins

- src/view/components/profiler/components/CommitTimeline/CommitTimeline.tsx
- src/view/components/profiler/components/TimelineBar/TimelineBar.tsx
> Improve Commit-Timeline display

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
> Release 1.0.0

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
> Release 1.0.1

- CHANGELOG.md
- package.json
- src/shells/chrome/manifest.json
- src/shells/edge/manifest.json
- src/shells/firefox/manifest.json
> Release 1.1.0

- .changeset/tough-walls-sneeze.md
- src/adapter/10/renderer.ts
- src/adapter/dom.ts
- src/constants.ts
> Use more robust Text node checks

- .changeset/friendly-kings-smile.md
- src/view/components/Devtools.css
- src/view/components/elements/TreeView.css
Some minor color palette changes to increase readability.
> Fix key hard to read in light theme in elements panel

- package.json
- yarn.lock
This was caused by an upstream bug in my stack trace parsing lib.
> Fix crash on stack trace parsing

- .editorconfig
Used this to stop my editor default settings getting into a fight.
Lost the battle with complete sanity as prettier itself is not sane, https://github.com/prettier/prettier/issues/4199 in particular being closed as WONTFIX is bonkers.
> Add .editorconfig to match prettier config

- src/adapter/10/renderer.ts
- src/shells/shared/panel/settings.ts
- src/view/components/elements/TreeBar.tsx
- src/view/components/settings/Settings.css
- src/view/components/settings/Settings.tsx
- src/view/store/filter.ts
- test-e2e/test-utils.ts
- test-e2e/tests/hoc-experimental.test.ts
- test-e2e/tests/hoc-filter-disable.test.ts
- test-e2e/tests/hoc-filter-search.test.ts
- test-e2e/tests/hoc-filter-update.test.ts
- test-e2e/tests/hoc-filter.test.ts
It's not ready yet and therefore I don't feel comfortable to enable it by default.
> Move HOC-Component filter behind a feature flag

- package.json
> Remove superfluous yarn command

- src/adapter/10/options.ts
- test-e2e/fixtures/hooks-multiple.js
- test-e2e/fixtures/test.html
- test-e2e/fixtures/vendor/preact/10.5.9/preact.js
- test-e2e/fixtures/vendor/preact/10.5.9/preactCompat.js
- test-e2e/fixtures/vendor/preact/10.5.9/preactDebug.js
- test-e2e/fixtures/vendor/preact/10.5.9/preactDevtools.js
- test-e2e/fixtures/vendor/preact/10.5.9/preactHooks.js
- test-e2e/test-utils.ts
- test-e2e/tests/hooks/hooks-multiple.test.ts
> Fix only first hooks shown if multiple listeners to options._hook were present

- src/adapter/10/utils.test.tsx
- src/adapter/10/utils.ts
- src/view/components/DataInput/index.tsx
- src/view/components/DataInput/parseValue.ts
- src/view/components/sidebar/inspect/parseProps.ts
- test-e2e/fixtures/apps/inspect-map-set.jsx
- test-e2e/tests/inspect-map-set.test.ts
> Add support for inspecting Map and Set objects

- src/adapter/10/renderer/hooks.ts
- src/adapter/10/utils.ts
- src/view/components/DataInput/parseValue.ts
- src/view/components/sidebar/inspect/parseProps.ts
- test-e2e/fixtures/apps/use-ref-element.jsx
- test-e2e/tests/hooks/useRef-element.test.ts
> Fix HTML refs being serialized to objects

- .github/workflows/nodejs.yml
- src/view/components/stats/StatsPanel.tsx
- Fix TS build error
- Build extension in CI to catch these errors
- User newer GitHub actions
> Fix TS build error

- src/view/components/elements/TreeView.tsx
- src/view/components/elements/VirtualizedList.tsx
- test-e2e/fixtures/apps/deep-tree-2.jsx
- test-e2e/tests/inspect-virtual.test.ts
> Fix virtualized elements not scrolled into view

- src/view/store/filter.ts
> Fix not all filters synced

- src/adapter/shared/traverse.ts
- src/view/components/elements/TreeView.tsx
- src/view/components/profiler/flamegraph/modes/FlamegraphLayout.tsx
- src/view/components/profiler/flamegraph/ranked/RankedLayout.tsx
- test-e2e/tests/hooks/hook-name.test.ts
- test-e2e/tests/profiler/flamegraph/utils.ts
Currently work in progress. Posting this as a todo for myself.
> Fix error with HOC filter when reordering nodes

- src/view/components/elements/TreeView.tsx
- src/view/components/elements/VirtualizedList.tsx
- test-e2e/test-utils.ts
Dynamically resize virtual list buffer based on container height
> Dynamically resize virtual list buffer

- src/adapter/shared/traverse.ts
- test-e2e/tests/hoc-update.test.ts
Follow up to #379 which commented out the fix, but we got a new test case out of it!
> Fix HOCs disappearing on update

- test-e2e/fixtures/apps/render-reasons-memo.jsx
- test-e2e/tests/profiler/render-reasons-memo.test.ts
I think I have a good idea on how to fix this, but it will take a bit of time as it touches a few areas.
Fixes #343
> Fix memo render reason

- src/adapter/10/options.ts
- src/adapter/debug.ts
- src/adapter/protocol/events.ts
- src/adapter/protocol/operations.ts
- src/adapter/shared/renderer.test.tsx
- src/adapter/shared/renderer.ts
- src/adapter/shared/stats.ts
- src/adapter/shared/traverse.ts
- src/view/components/stats/StatsPanel.tsx
- test-e2e/fixtures/apps/memo-stats.jsx
- test-e2e/tests/stats/stats-memo.test.ts
- Simplify stats capturing
- Skip memoized subtrees
> Improve stats capturing

- src/view/components/profiler/components/RenderedAt/RenderedAt.module.css
- src/view/components/profiler/components/RenderedAt/RenderedAt.tsx
- src/view/components/profiler/components/TimelineBar/TimelineBar.tsx
- src/view/components/profiler/data/commits.ts
- src/view/components/profiler/flamegraph/FlameGraph.module.css
- src/view/components/profiler/flamegraph/FlameGraph.tsx
- src/view/components/profiler/flamegraph/FlameNode.tsx
- src/view/components/profiler/flamegraph/modes/FlamegraphLayout.tsx
- src/view/components/profiler/flamegraph/modes/flamegraph-utils.ts
- src/view/components/profiler/flamegraph/modes/patchTree.ts
- src/view/components/profiler/flamegraph/ranked/RankedLayout.tsx
- test-e2e/tests/profiler/flamegraph/profiler-flamegraph-focus.test.ts
- test-e2e/tests/profiler/flamegraph/profiler-unaffected.test.ts
- test-e2e/tests/profiler/flamegraph/utils.ts
- test-e2e/tests/profiler/ranked/profiler-ranked-focus.test.ts
- Reset selection on commit change
- Add sidebar navigation for commit root
- Use a virtualized list for scrolling
> Profiler UX improvements

- tools/build.mjs
Fixes https://github.com/preactjs/signals/issues/47 .
> Fix mixed preact debug builds

- src/adapter/shared/hooks.ts
- test-e2e/fixtures/apps/hooks-name-custom.jsx
- test-e2e/tests/hooks/hook-name.test.ts
> Fix hook name applied to custom hook

- src/adapter/shared/serialize.ts
- test-e2e/fixtures/apps/props.jsx
- test-e2e/tests/hooks/hooks-depth-limit.test.ts
- test-e2e/tests/inspect-props-sort.test.ts
- test-e2e/tests/inspect-scroll.test.ts
- test-e2e/tests/inspect-truncate.test.ts
- test-e2e/tests/prop-input.test.ts
Makes debugging complex objects a little easier
> Sort inspected object properties

- src/adapter/10/options.ts
- src/adapter/10/renderReason.ts
- src/adapter/protocol/events.ts
- src/adapter/shared/hooks.ts
- src/adapter/shared/renderReasons.ts
- src/view/components/Devtools.module.css
- src/view/components/devtools.css
- src/view/components/profiler/components/RenderReasons.tsx
- src/view/components/profiler/data/commits.ts
- src/view/components/sidebar/inspect/ElementProps.tsx
- src/view/components/sidebar/inspect/parseProps.ts
- test-e2e/fixtures/load-preact-version.ts
- test-e2e/tests/hooks/hooks-number.test.ts
- test-e2e/tests/profiler/render-reasons.test.ts
> Display hook index
